### ISSUE TITLE
Pin Naming for GPIO Adapter

### ISSUE THREAD

**Issue by mrstegeman** [WebThingsIO/gpio-adapter#12]
Originally from: https://github.com/mozilla-iot/gateway/issues/681

The example at [Configuring GPIO for use with the gpio adapter](https://github.com/mozilla-iot/wiki/wiki/Configuring-GPIO-for-use-with-the-gpio-adapter) uses `pin 18`.

```
{
  "pins": {
    "18": {
      "direction": "out",
      "name": "led",
      "value": 0
    }
  }
}
``` 

However, there are two ways of numbering the pins:

+ GPIO numbering
![gpio-numbers-pi2](https://user-images.githubusercontent.com/951776/36298977-1eafd6cc-12fb-11e8-8f9e-30f235eead18.png)

+ Physical numbering
![physical-pin-numbers](https://user-images.githubusercontent.com/951776/36298980-2190dbb6-12fb-11e8-9905-6907ed99de3c.png)

See [Appendix 1. A note on pin numbering](https://www.raspberrypi.org/documentation/usage/gpio-plus-and-raspi2/README.md).

Wouldn't `GPIOs` instead on `Pins` be more adequate?

```
{
  "gpios": {
    "18": {
      "direction": "out",
      "name": "led",
      "value": 0
    }
  }
}
```

**Comment by dhylands** [comment]
I'd be happy to rename this as gpios. We'd probably want the code to look for both (preferring gpio, but allowing pins for backwards compatability)

We use the numbering scheme used by the gpio subsystem of the linux kernel, which isn't related to the numbering on the connector, but rather related to the GPIO numbering on the CPU chip.

**Comment by Geoff46** [comment]
I've just started using the Mozilla-iot gateway to control the GPIOs on a Raspberry Pi.
I've successfully set it up to turn a pin on and off. However I want to change the name I originally gave the button when setting it up. I have changed the name in the GPIO configuration screen but when I go back to the control screen it still has the old name. I've tried re-scanning but it still doesn't update to the new name.
What am I missing?
Grateful for any pointers.
Thanks

**Comment by Geoff46** [comment]
As an addition to my previous post: I tried adding another button in the GPIO configuration with the new name but it doesn't appear in the control screen.
I deleted the original button from the GPIO configuration but it still appears.
I will try removing the GPIO addon completely and then re-installing it.

**Comment by Geoff46** [comment]
Well, I'm getting nowhere - whatever I do the interface has permanently set itself on what I originally added. I can't change it, delete the old, or add any new, button to control the GPIO.
I'm stumped!

**Comment by Geoff46** [comment]
Just notice this thread is closed - I will start a new one.
