### ISSUE TITLE
GPIO-adapter does not work in Gateway 0.5.2

### ISSUE THREAD

**Issue by pchri** [WebThingsIO/gpio-adapter#25]
The GPIO adapter fails to load in Gateway 0.5.2 (and maybe earlier versions too)

```
> 2018-09-09 22:34:28.179 Fetching add-on https://s3-us-west-2.amazonaws.com/mozilla-gateway-addons/gpio-adapter-0.4.0-linux-arm-v8.tgz as /tmp/mcfbMn/gpio-adapter.tar.gz
> 2018-09-09 22:34:29.833 Expanding add-on /tmp/mcfbMn/gpio-adapter.tar.gz into /home/pchris/.mozilla-iot/addons/gpio-adapter
> 2018-09-09 22:34:30.293 Loading add-on: gpio-adapter
> 2018-09-09 22:34:31.200 gpio: Opening database: /home/pchris/.mozilla-iot/config/db.sqlite3
> 2018-09-09 22:34:31.244 gpio: Loading add-on for gpio-adapter from /home/pchris/.mozilla-iot/addons/gpio-adapter
> 2018-09-09 22:34:31.260 Plugin: gpio-adapter died, code = 100 NOT restarting...
```
It actually fails at line 12
`
const Gpio = require('onoff').Gpio;` 

I am not yet sufficiently at home in this to be able to debug it.

**Comment by dhylands** [comment]
Which platform are you trying this on? I just tested on the raspberry pi (running 0.5.3 version of gateway, but 0.4.0 version of gpio-adapter) and it seems to load fine.

**Comment by pchri** [comment]
Sorry. You're right. I can't reproduce this. This was on my RPi3. It makes no sense. Closing.
