### ISSUE TITLE
Add momentary support

### ISSUE THREAD

**Issue by mattalexhoward** [WebThingsIO/gpio-adapter#29]
As a user, 
I'd like to have a quick cycle of the GPIO pins 
for wider applications.

Ex: A garage door opener could be operated if there were support for a momentary switch.

**Comment by dhylands** [comment]
If you select "rising" (or falling depending on the input) then you'll detect a momentary input.

Perhaps a better request would be to have events generated on rising or falling edges.

Or perhaps you're looking for an output pulse?

There is a pulse adapter which can be used to generate pulses of arbitrary width.

**Comment by mrstegeman** [comment]
You'll want to combine the GPIO adapter with the [pulse adapter](https://github.com/mozilla-iot/pulse-adapter).

For more details, see the discussion [here](https://github.com/mozilla-iot/gpio-adapter/issues/27).

**Comment by mattalexhoward** [comment]
Ah, I see. Thanks for the help. It may be more UX friendly to add the pulse option to the GPIO adapter as a check box or something. I'm not sure what the scope of this add-on is so please close this issue if this request does not fit well. 

Thanks!

**Comment by mrstegeman** [comment]
Fixed by #42.
