### ISSUE TITLE
Missing "in" direction

### ISSUE THREAD

**Issue by rool80** [WebThingsIO/gpio-adapter#37]
I connected the motion sensor **HC-SR501** to raspberry pi 2 on pin gpio 2. Then when I go to the GPIO configuration and want to set the direction as "in", I can't see it there. I only have to choose "in - BinarySensor" and "in - PushButton". What am I doing wrong?

![image](https://user-images.githubusercontent.com/18568139/70573846-0f633300-1ba3-11ea-80be-234af662065e.png)

Dakujem za pomoc

**Comment by mrstegeman** [comment]
They'll both interpret the GPIO as `in`. The difference is just in what the adapter will represent the device as. In your case, you'll want `in - BinarySensor`.
