### ISSUE TITLE
seeed studio board won't work

### ISSUE THREAD

**Issue by chefrocker** [WebThingsIO/gpio-adapter#9]
The gpio's doesn't work with the seeed sensors and actors. that was very nice to test some function

**Comment by dhylands** [comment]
Could you be a bit more specific about what worked (or didn't work). Currently only GPIO 18 is defined. However, it is possible to enable other GPIOs (I'll write up a Wiki page on how to do that)

**Comment by chefrocker** [comment]
ok, i doesn't read that. For raspberry pi it gives a dev. board called seeed board that you can bring on the gpio's to easy connect some sensors. that board doesn't work at the moment. but i read the wiki first, it can be my issue. thanks

**Comment by dhylands** [comment]
If you're thinking of the grove adapter board, then it should be able to support the GPIO based sensors, but not the ones that use I2C or SPI (which will wind up being quite a few of them).
I added the wiki page here: https://github.com/mozilla-iot/wiki/wiki/Configuring-GPIO-for-use-with-the-gpio-adapter and if you installed the gpio-adapter prior to this, you should remove it and reinstall it.

**Comment by rzr** [comment]
I confirm, custom gpio pin can be used, (eventually we could had a graphical GUI that show pinout of different boards)

Please list reference of sensors / actuator you want to use?

This might help too:
https://s-opensource.org/2018/04/25/mozilla-iot-generic-sensors/

Good luck
